### ISSUE TITLE
[Question] woriking with ppc64le

### ISSUE THREAD

**Issue by AlessandroZavoli** [conda-forge/py-spy-feedstock#5]
Is it possible to make it work on ppc64le architecture?

Alessandro

**Comment by jack-pappas** [comment]
Rust (as of right now) has complete Tier 2 support for the ``powerpc64le-unknown-linux-gnu`` target; that target requires glibc 2.17, but so does py-spy itself, and now that #6 has been merged we're already requiring that glibc version for Linux packages.

If the conda-forge build infrastructure supports ``ppc64le`` package builds, it seems like it should be possible (at least in theory) to build this now.

**Comment by AlessandroZavoli** [comment]
Thank you for this answer!
Could you be a little more precise on the steps i have to perform? I'm not that expert with package building

**Comment by ticlazau** [comment]
Hello 
has this issue been solved?

Rgds,
FM

**Comment by AlessandroZavoli** [comment]
my HPCsupport office did it, still I don't know how
